### ISSUE TITLE
API无响应

### ISSUE THREAD

**Issue by Rhythmicc** [PasteUs/PasteMeGoBackend#86]
如题，尝试访问：[测试连接](https://pasteme.cn/100)，可看到如下内容：

```cpp
#include <bits/stdc++.h>
int main() {
	std::cout << "Hello World!" << std::endl;
	return 0;
}
```

当我尝试使用: https://api.pasteme.cn/100 ，且HTTP HEADER为以下内容时：

```yml
Request URL: https://api.pasteme.cn/100
Referrer Policy: strict-origin-when-cross-origin

sec-ch-ua: "Chromium";v="88", "Google Chrome";v="88", ";Not A Brand";v="99"
sec-ch-ua-mobile: ?0
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36
```

API无响应，这个问题已经许久了，是否考虑修复或继续支持API调用？
